Further template propagation to fix offload build
williamfgc/qmcpack pull request #30
Opened 2023-09-07 18:26 UTC by PhilipFackler

2023-09-13 15:17 UTC, williamfgc requested changes

2023-09-13 15:17 UTC, williamfgc commented on src/Numerics/OneDimGridFactory.h
> +struct OneDimGridFactory
Do we need to create a separate OneDimGridFactoryT ?

2023-09-13 15:17 UTC, williamfgc commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
@PhilipFackler let's make sure we are using a recent clang-format like clang-format-16 (that's what I am using).

2023-09-13 15:17 UTC, williamfgc commented on src/Numerics/OneDimGridFactory.h
> +struct OneDimGridFactory
@PhilipFackler

2023-09-13 15:21 UTC, PhilipFackler commented on src/Numerics/OneDimGridFactory.h
> +struct OneDimGridFactory
No. It's only used in one place.

2023-09-13 15:24 UTC, PhilipFackler commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
Looks like I didn't format that file.

2023-09-13 15:26 UTC, williamfgc commented on src/Numerics/OneDimGridFactory.h
> +struct OneDimGridFactory
OK, thanks for clarifying 👍

2023-09-13 15:27 UTC, williamfgc commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
Please check other files or an automatic way to format-on-save on your IDE. It pollutes the PR changes. Thanks!

2023-09-13 15:38 UTC, PhilipFackler commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
Just kidding, I did format this file. And now I don't see the problem.

2023-09-13 19:00 UTC, PhilipFackler commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
@williamfgc what would you like me to do about this?

2023-09-14 00:05 UTC, williamfgc commented on src/QMCWaveFunctions/ElectronGas/FreeOrbitalT.h
> +    const std::vector<PosType> kvecs; // kvecs vectors
Should be good now, thanks!

2023-09-14 00:05 UTC, merged